# Basic Configuration for Technical RAG System

# --- Data Paths ---
data_paths:
  raw_ebooks: "data/raw"
  processed_data: "data/processed"
  vector_db: "data/processed/chroma_db" # Example path for ChromaDB persistence

# --- Processing Settings ---
processing:
  chunk_size: 500       # Target token size for chunks
  chunk_overlap: 50     # Token overlap between chunks
  # Add more processing settings later (e.g., specific parsers)

# --- Embedding Settings ---
embedding:
  model_name: "all-MiniLM-L6-v2" # Default Sentence Transformer model
  # Add Gemini embedding settings if applicable later
  cache_folder: "data/processed/embedding_cache"

# --- Retrieval Settings ---
retrieval:
  k_results: 5          # Number of chunks to retrieve
  similarity_threshold: 0.7 # Minimum similarity score

# --- Generation Settings ---
generation:
  model_name: "models/gemini-2.0-pro-exp" # Updated to use gemini-2.0-pro-exp model
  max_output_tokens: 1024
  temperature: 0.7

# --- Logging ---
logging:
  log_file: "logs/app.log"
  log_level: "INFO" # e.g., DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_bytes: 10485760 # 10MB
  backup_count: 5

# --- API Keys ---
# API keys should ideally be loaded from environment variables (.env file)
# Example structure if needed, but prefer .env
# api_keys:
#   gemini: "LOAD_FROM_ENV" 